
spring.application.name=magic-mission-archive
spring.datasource.url=jdbc:postgresql://localhost:5432/jujutsukaisen_archive
spring.datasource.username=postgres
spring.datasource.password=vma25062005
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

